//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_ChgPwd : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_ChgPwd defaultInstance = ((Data_ChgPwd)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_ChgPwd())));
        
        public static Data_ChgPwd Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Changement du mot de passe admisnitrateur")]
        public string ChgPwdTitle {
            get {
                return ((string)(this["ChgPwdTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le mot de passe doit être supérieur à 7 caractères.")]
        public string IsPwdLengthInfSeven {
            get {
                return ((string)(this["IsPwdLengthInfSeven"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Les mots de passe ne sont pas identiques.")]
        public string ArePasswordNotEqual {
            get {
                return ((string)(this["ArePasswordNotEqual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L\'ancien mot de passe est incorrect.")]
        public string IsUsnAndPwdCheck {
            get {
                return ((string)(this["IsUsnAndPwdCheck"]));
            }
        }
    }
}
