//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_VaultDatabase : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_VaultDatabase defaultInstance = ((Data_VaultDatabase)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_VaultDatabase())));
        
        public static Data_VaultDatabase Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"|DataDirectory|\\Vault Database\\Data" +
            "base\\Vault.mdf\";Integrated Security=True")]
        public string VaultDatabaseConnectionString {
            get {
                return ((string)(this["VaultDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.IsFirstLaun" +
            "ch\".")]
        public string IsFirstLaunch {
            get {
                return ((string)(this["IsFirstLaunch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.SaveUsnAndP" +
            "wd\".")]
        public string SaveUsnAndPwd {
            get {
                return ((string)(this["SaveUsnAndPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetVaultID\"" +
            ".")]
        public string GetVaultID {
            get {
                return ((string)(this["GetVaultID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.CheckUsnAnd" +
            "Pwd\".")]
        public string CheckUsnAndPwd {
            get {
                return ((string)(this["CheckUsnAndPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.CheckCatego" +
            "ry\".")]
        public string CheckCategory {
            get {
                return ((string)(this["CheckCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.SaveCategor" +
            "y\".")]
        public string SaveCategory {
            get {
                return ((string)(this["SaveCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetVaultNam" +
            "e\".")]
        public string GetVaultName {
            get {
                return ((string)(this["GetVaultName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardNum" +
            "ber\".")]
        public string GetACardNumber {
            get {
                return ((string)(this["GetACardNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteN" +
            "umber\".")]
        public string GetScrNoteNumber {
            get {
                return ((string)(this["GetScrNoteNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetCategory" +
            "ID\".")]
        public string GetCategoryID {
            get {
                return ((string)(this["GetCategoryID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.UpdVaultNam" +
            "e\".")]
        public string UpdVaultName {
            get {
                return ((string)(this["UpdVaultName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.UpdateUsnAn" +
            "dPwd\".")]
        public string UpdateUsnAndPwd {
            get {
                return ((string)(this["UpdateUsnAndPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetCategori" +
            "eNameList\".")]
        public string GetCategorieNameList {
            get {
                return ((string)(this["GetCategorieNameList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.DeleteCateg" +
            "ory\".")]
        public string DeleteCategory {
            get {
                return ((string)(this["DeleteCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.UpdateACard" +
            "Category\".")]
        public string UpdateACardCategory {
            get {
                return ((string)(this["UpdateACardCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.UpdateScrNo" +
            "teCategory\".")]
        public string UpdateScrNoteCategory {
            get {
                return ((string)(this["UpdateScrNoteCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.UpdateCateg" +
            "ory\".")]
        public string UpdateCategory {
            get {
                return ((string)(this["UpdateCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.SaveAuthenC" +
            "ard\".")]
        public string SaveAuthenCard {
            get {
                return ((string)(this["SaveAuthenCard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardShc" +
            "List\".")]
        public string GetACardShcList {
            get {
                return ((string)(this["GetACardShcList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardUsn" +
            "List\".")]
        public string GetACardUsnList {
            get {
                return ((string)(this["GetACardUsnList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.CheckAuthen" +
            "Card\".")]
        public string CheckAuthenCard {
            get {
                return ((string)(this["CheckAuthenCard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.UpdateAuthe" +
            "nCardData\".")]
        public string UpdateAuthenCardData {
            get {
                return ((string)(this["UpdateAuthenCardData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.DeleteAuthe" +
            "nCard\".")]
        public string DeleteAuthenCard {
            get {
                return ((string)(this["DeleteAuthenCard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardNam" +
            "eList\".")]
        public string GetACardNameList {
            get {
                return ((string)(this["GetACardNameList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardCpx" +
            "FactorList\".")]
        public string GetACardCpxFactorList {
            get {
                return ((string)(this["GetACardCpxFactorList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardIDL" +
            "ist\".")]
        public string GetACardIDList {
            get {
                return ((string)(this["GetACardIDList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteB" +
            "ookmark\".")]
        public string GetScrNoteBookmark {
            get {
                return ((string)(this["GetScrNoteBookmark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardCrt" +
            "Date\".")]
        public string GetACardCrtDate {
            get {
                return ((string)(this["GetACardCrtDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardChg" +
            "Date\".")]
        public string GetACardChgDate {
            get {
                return ((string)(this["GetACardChgDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardScr" +
            "NoteList\".")]
        public string GetACardScrNoteList {
            get {
                return ((string)(this["GetACardScrNoteList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetACardCat" +
            "egory\".")]
        public string GetACardCategory {
            get {
                return ((string)(this["GetACardCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.SaveScrNote" +
            "\".")]
        public string SaveScrNote {
            get {
                return ((string)(this["SaveScrNote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.CheckScrNot" +
            "eName\".")]
        public string CheckScrNoteName {
            get {
                return ((string)(this["CheckScrNoteName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.UpdateScrNo" +
            "teData\".")]
        public string UpdateScrNoteData {
            get {
                return ((string)(this["UpdateScrNoteData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.DeleteScrNo" +
            "te\".")]
        public string DeleteScrNote {
            get {
                return ((string)(this["DeleteScrNote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteC" +
            "ategory\".")]
        public string GetScrNoteCategory {
            get {
                return ((string)(this["GetScrNoteCategory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteC" +
            "rtDate\".")]
        public string GetScrNoteCrtDate {
            get {
                return ((string)(this["GetScrNoteCrtDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteC" +
            "hgDate\".")]
        public string GetScrNoteChgDate {
            get {
                return ((string)(this["GetScrNoteChgDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteN" +
            "ameList\".")]
        public string GetScrNoteNameList {
            get {
                return ((string)(this["GetScrNoteNameList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteC" +
            "ontentList\".")]
        public string GetScrNoteContentList {
            get {
                return ((string)(this["GetScrNoteContentList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"VaultDatabase.GetScrNoteI" +
            "DList\".")]
        public string GetScrNoteIDList {
            get {
                return ((string)(this["GetScrNoteIDList"]));
            }
        }
    }
}
