//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_PwdGen : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_PwdGen defaultInstance = ((Data_PwdGen)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_PwdGen())));
        
        public static Data_PwdGen Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AZERTYUIOPQSDFGHJKLMWXCVBN")]
        public string letters {
            get {
                return ((string)(this["letters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0123456789")]
        public string numbers {
            get {
                return ((string)(this["numbers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!\"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~")]
        public string symbols {
            get {
                return ((string)(this["symbols"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A-Z")]
        public string regexUpper {
            get {
                return ((string)(this["regexUpper"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a-z")]
        public string regexLower {
            get {
                return ((string)(this["regexLower"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0-9")]
        public string regexNumbers {
            get {
                return ((string)(this["regexNumbers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!\"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~")]
        public string regexSymbols {
            get {
                return ((string)(this["regexSymbols"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inutile")]
        public string cpxCmtVeryBad {
            get {
                return ((string)(this["cpxCmtVeryBad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gringalet")]
        public string cpxCmtBad {
            get {
                return ((string)(this["cpxCmtBad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Musclé")]
        public string cpxCmtGood {
            get {
                return ((string)(this["cpxCmtGood"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fantastique")]
        public string cpxCmtFantastic {
            get {
                return ((string)(this["cpxCmtFantastic"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"PwdGen.GetRandomPwd\".")]
        public string GetRandomPwd {
            get {
                return ((string)(this["GetRandomPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Générateur de mots de passe")]
        public string PwdGenTitle {
            get {
                return ((string)(this["PwdGenTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Veuillez sélectionner au moins une option.")]
        public string IsCheckedAnyCase {
            get {
                return ((string)(this["IsCheckedAnyCase"]));
            }
        }
    }
}
