//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_AES : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_AES defaultInstance = ((Data_AES)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_AES())));
        
        public static Data_AES Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.DecryptData\"" +
            ".")]
        public string DecryptData {
            get {
                return ((string)(this["DecryptData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.EncryptData\"" +
            ".")]
        public string EncryptData {
            get {
                return ((string)(this["EncryptData"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Salt {
            get {
                return ((string)(this["Salt"]));
            }
            set {
                this["Salt"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.GetKeyAndIV\"" +
            ".")]
        public string GetKeyAndIV {
            get {
                return ((string)(this["GetKeyAndIV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.GetRandomSal" +
            "t\".")]
        public string GetRandomSalt {
            get {
                return ((string)(this["GetRandomSalt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.IsDataLength" +
            "_Error\".")]
        public string IsDataLength_Error {
            get {
                return ((string)(this["IsDataLength_Error"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.IsPwdLength_" +
            "Error\".")]
        public string IsPwdLength_Error {
            get {
                return ((string)(this["IsPwdLength_Error"]));
            }
        }
    }
}
