//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_Authen : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_Authen defaultInstance = ((Data_Authen)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_Authen())));
        
        public static Data_Authen Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Confirmation du mot de passe")]
        public string AddAuthenLabelPassword_2 {
            get {
                return ((string)(this["AddAuthenLabelPassword_2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Connexion")]
        public string AuthenTitle {
            get {
                return ((string)(this["AuthenTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le nom d\'utilisateur ou le mot de passe n\'ont pas été saisi.")]
        public string IsUsnAndPwdEmpty {
            get {
                return ((string)(this["IsUsnAndPwdEmpty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le mot de passe doit être supérieur à 7 caractères.")]
        public string IsPwdLengthInfSeven {
            get {
                return ((string)(this["IsPwdLengthInfSeven"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Les mots de passe ne sont pas identiques.")]
        public string ArePasswordNotEqual {
            get {
                return ((string)(this["ArePasswordNotEqual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le nom d\'utilisateur ou le mot de passe est incorrect.")]
        public string IsUsnAndPwdCheck {
            get {
                return ((string)(this["IsUsnAndPwdCheck"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tous les éléments")]
        public string AllItem {
            get {
                return ((string)(this["AllItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Personnel")]
        public string Personnal {
            get {
                return ((string)(this["Personnal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Professionnel")]
        public string Professional {
            get {
                return ((string)(this["Professional"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Messagerie Electronique")]
        public string Mailbox {
            get {
                return ((string)(this["Mailbox"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Réseaux Sociaux")]
        public string SocialNetwork {
            get {
                return ((string)(this["SocialNetwork"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Compte Bancaire")]
        public string Bank {
            get {
                return ((string)(this["Bank"]));
            }
        }
    }
}
