//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_Category : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_Category defaultInstance = ((Data_Category)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_Category())));
        
        public static Data_Category Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Catégorie")]
        public string CategoryTitle {
            get {
                return ((string)(this["CategoryTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le nom de la catégorie est incorrecte.")]
        public string IsCtgNameLength_Error {
            get {
                return ((string)(this["IsCtgNameLength_Error"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cette catégorie existe déjà.")]
        public string IsCategoryExist {
            get {
                return ((string)(this["IsCategoryExist"]));
            }
        }
    }
}
