//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_Hash : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_Hash defaultInstance = ((Data_Hash)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_Hash())));
        
        public static Data_Hash Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.CheckHash\".")]
        public string CheckHash {
            get {
                return ((string)(this["CheckHash"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Salt {
            get {
                return ((string)(this["Salt"]));
            }
            set {
                this["Salt"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.GetHash\".")]
        public string GetHash {
            get {
                return ((string)(this["GetHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.GetRandomSal" +
            "t\".")]
        public string GetRandomSalt {
            get {
                return ((string)(this["GetRandomSalt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Une erreur s\'est produite lors de l\'accès à la méthode \"AESAlgorithm.IsDataLength" +
            "_Error\".")]
        public string IsDataLength_Error {
            get {
                return ((string)(this["IsDataLength_Error"]));
            }
        }
    }
}
