//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_RnmVault : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_RnmVault defaultInstance = ((Data_RnmVault)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_RnmVault())));
        
        public static Data_RnmVault Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Changement du nom du coffre-fort virtuel")]
        public string RnmVaultTitle {
            get {
                return ((string)(this["RnmVaultTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le nom du coffre-fort est incorrect.")]
        public string IsVltNameLength_Error {
            get {
                return ((string)(this["IsVltNameLength_Error"]));
            }
        }
    }
}
