//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_Home : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_Home defaultInstance = ((Data_Home)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_Home())));
        
        public static Data_Home Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Accueil")]
        public string HomeTitle {
            get {
                return ((string)(this["HomeTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Enregistrement(s)")]
        public string ItemLegendNbr {
            get {
                return ((string)(this["ItemLegendNbr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aucun élément existant.")]
        public string lbl_anyItem_Content {
            get {
                return ((string)(this["lbl_anyItem_Content"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Renommer ")]
        public string AddCategoryControls_Rename {
            get {
                return ((string)(this["AddCategoryControls_Rename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supprimer ")]
        public string AddCategoryControls_Delete {
            get {
                return ((string)(this["AddCategoryControls_Delete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Suppression d\'une catégorie")]
        public string lbl_MenuItemDelete_Click_Title_Category {
            get {
                return ((string)(this["lbl_MenuItemDelete_Click_Title_Category"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Etes-vous sûr de vouloir supprimer cette catégorie ?")]
        public string lbl_MenuItemDelete_Click_Message_Category {
            get {
                return ((string)(this["lbl_MenuItemDelete_Click_Message_Category"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fiches d\'authentification")]
        public string lbl_aCardSection_Content {
            get {
                return ((string)(this["lbl_aCardSection_Content"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Notes sécurisées")]
        public string lbl_scrNoteSection_Content {
            get {
                return ((string)(this["lbl_scrNoteSection_Content"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" % efficace")]
        public string lbl_aCardCpxFactor_Content {
            get {
                return ((string)(this["lbl_aCardCpxFactor_Content"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Modifier")]
        public string lbl_mainDataUpdate {
            get {
                return ((string)(this["lbl_mainDataUpdate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Supprimer")]
        public string lbl_mainDataDelete {
            get {
                return ((string)(this["lbl_mainDataDelete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("authenCardID_")]
        public string authenCardID {
            get {
                return ((string)(this["authenCardID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copier nom d\'utilisateur")]
        public string cmd_aCardCopyUsn {
            get {
                return ((string)(this["cmd_aCardCopyUsn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copier mot de passe")]
        public string cmd_aCardCopyPwd {
            get {
                return ((string)(this["cmd_aCardCopyPwd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Etes-vous sûr de vouloir supprimer cette fiche d\'authentification ?")]
        public string lbl_MenuItemDelete_Click_Message_AuthenCard {
            get {
                return ((string)(this["lbl_MenuItemDelete_Click_Message_AuthenCard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Etes-vous sûr de vouloir supprimer cette note sécurisée ?")]
        public string lbl_MenuItemDelete_Click_Message_ScrNote {
            get {
                return ((string)(this["lbl_MenuItemDelete_Click_Message_ScrNote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("scrNoteID_")]
        public string scrNoteID {
            get {
                return ((string)(this["scrNoteID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Suppression d\'une fiche d\'authentification")]
        public string lbl_MenuItemDelete_Click_Title_AuthenCard {
            get {
                return ((string)(this["lbl_MenuItemDelete_Click_Title_AuthenCard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Suppression d\'une note sécurisée")]
        public string lbl_MenuItemDelete_Click_Title_ScrNote {
            get {
                return ((string)(this["lbl_MenuItemDelete_Click_Title_ScrNote"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tous les éléments")]
        public string AllItems {
            get {
                return ((string)(this["AllItems"]));
            }
        }
    }
}
