//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVault.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Data_AuthenCard : global::System.Configuration.ApplicationSettingsBase {
        
        private static Data_AuthenCard defaultInstance = ((Data_AuthenCard)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Data_AuthenCard())));
        
        public static Data_AuthenCard Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Le nom de la fiche, le nom d\'utilisateur ou le mot de passe n\'a pas été saisi.")]
        public string IsACardDataNull {
            get {
                return ((string)(this["IsACardDataNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cette fiche d\'authentification existe déjà.")]
        public string IsAuthenCardExist {
            get {
                return ((string)(this["IsAuthenCardExist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fiche d\'authentification")]
        public string AuthenCardTitle {
            get {
                return ((string)(this["AuthenCardTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:yyyy-MM-dd}")]
        public string DateTimeFormat {
            get {
                return ((string)(this["DateTimeFormat"]));
            }
        }
    }
}
